export enum routes {
  astrologicalProcessor = '/processor',
  chats = '/chats',
  authorization = '/authorization',
  settings = '/settings',
  menu = '/menu',
  personal = '/personal',
  myHoroscopes = '/my-horoscopes',
  horoscopes = '/horoscopes',
  forum = '/forum',
  createTopic = '/create-topic',
  rates = '/rates',
  forumItem = '/forum-item',
  notifications = '/notifications',
  calendar = '/calendar',
  main = '/',
  Chat = '/chat',
  user = '/user',
  userEdit = '/user-edit',
  Courses = '/courses',
  levels = '/levels'
}
